title: Nighthawk Pages 
description: "Class of 2028"
owner_name: Elise Lin
github_username: blueelephant48
github_repo: "Elise_Portfolio_2025" 
baseurl: "/Elise_Portfolio_2025"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/rpg.md
  - navigation/game.md
  - navigation/kasm.md
  - navigation/blog.md
  - navigation/search.md